package org.example;// Generated by Selenium IDE


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Daft7Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public void daft7(String link) {

    driver = new ChromeDriver();
    driver.manage().deleteAllCookies();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    driver.get(link);
    driver.manage().window().setSize(new Dimension(1366, 703));
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".cc-modal__btn:nth-child(2)")).click();
    js.executeScript("window.scrollTo(0,330)");
    driver.findElement(By.cssSelector(".deYANw:nth-child(2) > .NewButton__StyledButton-yem86a-2 > .NewButton__ButtonText-yem86a-0")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("am.ahuja32@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Amit@1234");
    driver.findElement(By.name("login")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("keyword1")).click();
    driver.findElement(By.id("keyword1")).sendKeys("Amit Ahuja");
    driver.findElement(By.id("keyword2")).sendKeys("sai.amit.ahuja@gmail.com");
    driver.findElement(By.id("keyword3")).click();
    driver.findElement(By.id("keyword3")).sendKeys("0896133658");
    driver.findElement(By.id("message")).click();
    driver.findElement(By.id("message")).sendKeys("hi");
    driver.findElement(By.cssSelector(".Styles__ButtonContainer-sc-1sc49hg-9:nth-child(5) .NewButton__StyledButton-yem86a-2")).click();
    driver.close();
  }
}
